<a href="https://colab.research.google.com/github/NekoKumaSann/PyTorch_Tutorial/blob/main/%E8%B0%B7%E5%8F%A3%E7%A0%94_PyTorch%E7%B7%B4%E7%BF%92_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 応用情報工学演習（谷口研）深層学習ベースの画像認識 PyTorchの基本1

## PyTorch

PyTorch（パイトーチ）は、Pythonのオープンソース機械学習ライブラリ（Deep Learningライブラリ）です。

Facebookの人工知能研究グループAI Research lab（FAIR）により開発されました。

類似のライブラリとしては、[Keras](https://keras.io)や[TensorFlow](https://www.tensorflow.org)があります。

PyTorchは、最先端のディープラーニングの研究では主流となっています。
谷口研でも、PyTorchの利用が主流です。

以下は、PyTorchの公式資料です。適宜参照してください。

* [PyTorch公式サイト](https://pytorch.org/)
* [PyTorch Tutorials](https://pytorch.org/tutorials)
* [PyTorch documentation](https://pytorch.org/docs)

PyTorchの利用方法を確認しつつ、最終的にConvolutional Neural Network（CNN）による画像認識ができるようになることを目標とします。


**ライブラリインポート**

In [ ]:
# PyTorchライブラリ

import torch

In [ ]:
# その他のライブラリ

import numpy as np

## テンソル（Tensor）

PyTorchでは、演算対象のデータはすべてテンソル（Tensor）という独自のクラスで表現します。

テンソルはNumPyのndarraysに似ていますが、違いとしてGPUや他のハードウェアアクセラレータ上で動作させることができます。

また、ディープラーニングで重要な微分に最適化されています。

テンソルの基本的な使い方を確認します。

### テンソルの初期化

テンソルは様々な手法で初期化できます。

以下に例を示します。



**データから直接テンソルに変換**

データから直接テンソルを作ることができます。

その際、データ型は自動的に推測されます。


In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**NumPy arrayからテンソルに変換**

テンソルとNumpy arraysは相互に変換可能です。



In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**他のテンソルから作成**

他のテンソルから新しいテンソルを作成する場合、明示的に上書きされない限り、引数のテンソルのプロパティ（形状、データ型）を保持します。


In [ ]:
x_ones = torch.ones_like(x_data) # x_dataの特性（プロパティ）を維持
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_dataのdatatypeを上書き更新
print(f"Random Tensor: \n {x_rand} \n")

**ランダム値や定数のテンソルの作成**


``shape``は、テンソルの次元を示すタプルです。

以下の例では、shapeからテンソルのサイズを決めています。





In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

### テンソルの属性変数

テンソルは属性変数として、その形状、データの型、保存されているデバイスを保持しています。


In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

### テンソルの操作

PyTorchでは、算術、線形代数、行列操作（転置、インデックス、スライス）など、100種類以上のテンソル演算が可能です。

種々操作の詳細は[こちら](https://pytorch.org/docs/stable/torch.html)をご覧ください。



テンソル操作の中からいくつかを試してみましょう。

NumPy APIに慣れていれば、Tensor APIも簡単に使えるようになると思います。




**演習問題**

NumPyで学んだ操作をTensorでも試してみましょう。


In [ ]:
# 4 x 4のテンソルを作る
t = torch.tensor([[0.6217, 0.7413, 0.1310, 0.2747],
        [0.2945, 0.1933, 0.4784, 0.1593],
        [0.5192, 0.9683, 0.9831, 0.5339],
        [0.7758, 0.1899, 0.0394, 0.6244]])
print (t)

In [ ]:
# 最初の行を表示
t

# tensor([0.6217, 0.7413, 0.1310, 0.2747])

In [ ]:
# 最初の列を表示
t

# tensor([0.6217, 0.2945, 0.5192, 0.7758])

In [ ]:
# 最後の列を表示
t

# tensor([0.2747, 0.1593, 0.5339, 0.6244])

In [ ]:
# 2列目をすべて0にする
t

print(t) # tensor([[0.6217, 0.0000, 0.1310, 0.2747],
#                  [0.2945, 0.0000, 0.4784, 0.1593],
#                  [0.5192, 0.0000, 0.9831, 0.5339],
#                  [0.7758, 0.0000, 0.0394, 0.6244]])

**テンソルの結合**


``torch.cat``を使用することで、テンソルを特定の次元に沿って結合させることができます（詳細は[こちら](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)をご覧ください）。

``torch.cat``とは微妙に異なるテンソル結合演算である[``torch.stack``](https://pytorch.org/docs/stable/generated/torch.stack.html)も確認しておいてください。



In [ ]:
t0 = torch.rand(4, 4)
print(t0)
t1 = torch.cat([t0, t0, t0], dim=1)
print(t1)

In [ ]:
t0 = torch.rand(4, 4)
print(t0)
t1 = torch.stack([t0, t0, t0])
print(t1)

**算術演算**



In [ ]:
tensor = torch.rand(4, 4)

In [ ]:
# 2つのテンソル行列のかけ算です。 y1, y2, y3 は同じ結果になります。
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(f"y1:{y1}")
print(f"y2:{y2}")
print(f"y3:{y3}")

In [ ]:
# こちらは、要素ごとの積を求めます。 z1, z2, z3 は同じ値になります。
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(f"z1:{z1}")
print(f"z2:{z2}")
print(f"z3:{z3}")

**1要素のテンソル**

1要素のテンソル（テンソルの全要素を足し算する等をした結果生まれます）を扱う場合には、``.item()``を使用することでPythonの数値型変数に変換できます。




In [ ]:
tensor = torch.arange(0,10,1).reshape([5, 2])
print(tensor)

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item)) # int型であることを確認

### NumPyとの変換


CPU上のテンソルとNumpy arraysは同じメモリを共有することができ、相互変換が容易です。



**Tensor to NumPy array**



In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

この際、テンソルが変化すると、Numpy側も変化します。



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

**NumPy array to Tensor**



In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy arrayの変化はテンソル側にも反映されます（実体は同じ）。



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

### よく使う関数

**いろいろな階数のTensorを作る**

In [ ]:
# 0階テンソル (スカラー)
r0 = torch.tensor(1.0).float()

# typeを調べる
print(type(r0))

# dtypeを調べる
print(r0.dtype)

In [ ]:
# shapeを調べる
print(r0.shape)

# データを調べる
print(r0.data)

In [ ]:
# 1階テンソル (ベクトル)

# 1階のNumPy変数作成
r1_np = np.array([1, 2, 3, 4, 5])
print(r1_np.shape)

# NumPyからテンソルに変換
r1 = torch.tensor(r1_np).float()

# dtypeを調べる
print(r1.dtype)

# shapeを調べる
print(r1.shape)

# データを調べる
print(r1.data)

In [ ]:
# 2階テンソル (行列)

# 2階のNmPy変数作成
r2_np = np.array([[1, 5, 6], [4, 3, 2]])
print(r2_np.shape)

# NumPyからテンソルに変換
r2 = torch.tensor(r2_np).float()

# shapeを調べる
print(r2.shape)

# データを調べる
print(r2.data)

In [ ]:
# ３階テンソル

# 乱数seedの初期化
torch.manual_seed(123)

# shape=[3,2,2]の正規分布変数テンソルを作る
r3 = torch.randn((3, 2, 2))

# shapeを調べる
print(r3.shape)

# データを調べる
print(r3.data)

In [ ]:
# 4階テンソル

# shape=[2,3,2,2]の要素がすべて1のテンソルを作る
r4 = torch.ones((2, 3, 2, 2))

# shapeを調べる
print(r4.shape)

# データを調べる
print(r4.data)

**整数型テンソルを作る**

In [ ]:
# 整数型
r5 = r1.long()

# dtype　を確認
print(r5.dtype)

# 値を確認
print(r5)

**sum関数**

In [ ]:
# 総和計算
print(r1.sum())


**view関数**

In [ ]:
# 2階化

# shape=[3,2,2]の正規分布変数テンソルを作る
r3 = torch.randn((3, 2, 2))
print(r3)

# 要素数に-1を指定すると、この数を自動調整する
r6 = r3.view(3, -1)

# shape確認
print(r6.shape)

# 値確認
print(r6.data)

In [ ]:
# 1階化

# shape=[3,2,2]の正規分布変数テンソルを作る
r3 = torch.randn((3, 2, 2))
print(r3)

# 要素数に-1を指定すると、この数を自動調整する
r7 = r3.view(-1)

# shape確認
print(r7.shape)

# 値確認
print(r7.data)

**item関数**

In [ ]:
# スカラーテンソル(0階テンソル)に対してはitem関数で値を取り出せる

item = r0.item()

print(type(item))
print(item)

In [ ]:
# 0階以外のテンソルにitem関数は無効 (エラーになる)

print(r1.item())

In [ ]:
# 要素数が1つだけの1階テンソルはOK
# (2階以上でも同様)
t1 = torch.ones(1)

# shape確認
print(t1.shape)

# item関数呼び出し
print(t1.item())

**max関数**

In [ ]:
# 元テンソルr2の確認
print(r2)

# max関数を引数なしで呼び出すと、全体の最大値が取得できる
print(r2.max())

In [ ]:
# torch.max関数
# 2つめの引数はどの軸で集約するかを意味する
print(torch.max(r2, 1))

In [ ]:
# 何番目の要素が最大値をとるかは、indicesを調べればいい
# 以下の計算は、多値分類で予測ラベルを求めるときによく利用されるパターン
print(torch.max(r2, 1)[1])

### <練習問題1>

**<練習問題1-1>**

[1, 1, 0, 1, 0, 1, 1, 0, 1, 1]をもつ1階のテンソルytと[1, 1, 0, 1, 0, 1, 1, 1, 1, 1]をもつ1階のテンソルypを作成する。

In [ ]:
yt
yp

print(yt)
print(yp)

**<練習問題1-2>**

上記で作成したテンソルytとypの一致している要素数の総和を求める。

In [ ]:
# 1行でmatchedへ要素数の総和を代入
matched

print(matched)

# テスト、以下でエラーがでないことを確認
assert matched==9, f'Mismatched'

-----------

## 自動微分機能

ニューラルネットワークを訓練する際、その学習アルゴリズムとして、基本的にはバックプロパゲーション（back propagation）が使用されます。

バックプロパゲーションでは、モデルの重みなどの各パラメータは、損失関数に対するその変数の微分値（勾配）に応じて調整されます。

これらの勾配の値を計算するために、PyTorchにはtorch.autograd という微分エンジンが組み込まれています。

autogradはPyTorchの計算グラフに対する勾配の自動計算を支援します。


PyTorchで自動微分を行う場合の処理の流れを以下に示します。

1. 勾配計算用変数の定義  
requires_grad = Trueとする
1. テンソル変数間で計算  
裏で計算グラフが自動生成される
1. 勾配計算
1. 勾配値の取得  
grad属性
1. 勾配値の初期化  
zero_関数

2次関数を例にして、PyTorchで自動微分機能を確認しましょう。

## 2次関数の勾配計算

In [ ]:

# ライブラリインポート

%matplotlib inline
import torch
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display


In [ ]:
# matplotlibの設定

## デフォルトフォントサイズ変更
plt.rcParams['font.size'] = 14

## デフォルトグラフサイズ変更
plt.rcParams['figure.figsize'] = (6,6)

## デフォルトで方眼表示ON
plt.rcParams['axes.grid'] = True

 **データ準備**

In [ ]:
# xをnumpy配列で定義
x_np = np.arange(-2, 2.1, 0.25)

# xの値表示
print(x_np)

In [ ]:
# (1) 勾配計算用変数の定義
x = torch.tensor(x_np, requires_grad=True, dtype=torch.float32)

# 結果確認
print(x)

**２次関数の計算**

In [ ]:
# 2次関数の計算
# 裏で計算グラフが自動生成される

y = 2 * x**2 + 2

$ y = 2x^2 + 2$ を意味する

In [ ]:
# yの計算結果確認

print(y)

In [ ]:
# グラフ(散布図)描画

plt.plot(x.data, y.data)
plt.show()

In [ ]:
# 勾配計算のためには、最終値はスカラーの必要があるため、ダミーでsum関数をかける

z = y.sum()

In [ ]:
# (3) 勾配計算

z.backward()

In [ ]:
# (4) 勾配値の取得

print(x.grad)

In [ ]:
# 元の関数と勾配のグラフ化

plt.plot(x.data, y.data, c='b', label='y')
plt.plot(x.data, x.grad.data, c='k', label='y.grad')
plt.legend()
plt.show()

ここでもう一度勾配計算をしてみる。

In [ ]:
# 勾配の初期化せずに２度目の勾配計算

y = 2 * x**2 + 2
z = y.sum()
z.backward()

# xの勾配確認
print(x.grad)

勾配値は、勾配計算の結果がどんどん加算されてしまう。そのため新しい値を計算したい場合、勾配値のリセットが必要。

In [ ]:
# (5) 勾配の初期化は関数 zero_()を使う

x.grad.zero_()
print(x.grad)

## <練習問題2>

シグモイド関数の微分を行い、勾配をシグモイド関数とともに図示してみましょう。

シグモイド関数は数式で表すと次の形になります。

$ y = \dfrac{1}{1 + \exp{(-x)}} $

$\exp()$の計算としてPyTorchでは`torch.exp`関数が利用できます。

In [ ]:
%matplotlib inline
import torch
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

# シグモイド関数の定義
def sigmoid(x):


# 勾配計算用変数の定義
x_np = np.arange(-2, 2.1, 0.25)

# x_npをテンソル化したテンソルxを作成
x


# yの値の計算
y = sigmoid(x)

# 勾配計算のためには、最終値はスカラーの必要があるため、yをスカラー化したzを作成
z

# 勾配計算


# 勾配値の確認
print(x.grad)

# 元の関数と勾配のグラフ化
plt.plot(x.data, y.data, c='b', label='y')
plt.plot(x.data, x.grad.data, c='k', label='y.grad')
plt.legend()
plt.show()